# Starter pipeline
# Run the pipeline every day at 07:00 am on sunday until thrusday
# Only run on branches that contain the word 'dev' on a Linux system
# step 1: The run should print "hello world"
# step 2: Search for all files with the extension '.log'
# If the word 'ERROR' is found in any of those files, print 'FAIL'

trigger:
 -schedules:
   - cron: "0 7 * * 0-4"
   displayName: 'Run in 7:00 am sun-thr'
      branches:
        include: 
        - main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world! Have a good day
  displayName: 'Run Hello message'
- script: |
     error_output=$(grep -r ERROR *.log)
      if [ -z "$error_output"]; then 
      echo "PASS"
      else
      echo "FAIL"
      fi
  displayName: 'Check Error in logs file'
- script: |
   last_commit=$(git rev-parse HEAD)
   changed_files=$(git diff --name-only $last_commit HEAD)
      if [ -z "$changed_files"]; then 
      echo "No Changes"
      else
      echo "Changed_files:"
      echo "$changed_files"
      fi
  displayName: 'List Changed files'