# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
pool:
  vmImage: ubuntu-latest
schedules:
  - cron: "0 7 * * 0-4"
    displayName: 'Run in 7:00 am sun-thr'
    branches:
      include: 
      - main
steps:
- script: echo Hello, world! Have a good day
  displayName: 'Run a one-line script'
- script: |
     error_output=$(grep -r ERROR *.log)
      if [ -z "$error_output"]; then 
      echo "PASS"
      else
      echo "FAIL"
      fi
  displayName: 'Check Error in logs file'
- script: |
   git fetch
   last_commit=$(git rev-parse HEAD)
   changed_files=$(git diff --name-only $last_commit HEAD
   branches=($(echo "$changed_files" | awk -F/ '{print $1}' | sort -u))
   echo "Changed branches:"
    for branch in "${branches[@]}"; do
      echo "- $branch"
    done
  displayName: 'List Changed Branches'



